# 05 data type

In [1]:
import torch
import numpy as np

### Type check

In [2]:
a = torch.randn(2,3)
a

tensor([[ 1.9884,  0.3176,  1.9349],
        [-0.6929,  0.6348, -0.4185]])

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a, torch.FloatTensor)

True

### cpu的tensor和gpu的tensor不是一个 

In [6]:
isinstance(a, torch.cuda.FloatTensor)

False

In [7]:
a = a.cuda()

In [8]:
isinstance(a, torch.cuda.FloatTensor)

True

### Dimension 0 ==> loss

In [9]:
b = torch.tensor(2.2)
b

tensor(2.2000)

In [10]:
b.shape

torch.Size([])

In [11]:
b.size()

torch.Size([])

In [12]:
len(b.shape)

0

### Dimension 1 ==> bias

In [13]:
torch.tensor([1.1])

tensor([1.1000])

In [14]:
torch.tensor([1.1,2.2,3.3])

tensor([1.1000, 2.2000, 3.3000])

In [15]:
torch.FloatTensor(3)

tensor([3.6893e+19, 2.1625e+00,        nan])

In [16]:
c = np.ones(3)
c

array([1., 1., 1.])

In [17]:
d = torch.from_numpy(c)
d

tensor([1., 1., 1.], dtype=torch.float64)

In [18]:
d.shape

torch.Size([3])

### Dimension 2 ==> linear input batch

In [19]:
e = torch.randn(2, 3)
e

tensor([[-0.2044,  0.3417, -1.6704],
        [ 0.4386,  1.0106,  0.9038]])

In [20]:
e.shape

torch.Size([2, 3])

In [21]:
e.size(0)

2

In [22]:
e.size(1)

3

In [23]:
e.shape[1]

3

### Dimension 3 ==> RNN input batch

In [24]:
f = torch.rand(2,2,3)
f

tensor([[[0.2682, 0.9967, 0.4622],
         [0.3456, 0.1752, 0.2852]],

        [[0.6121, 0.2384, 0.3445],
         [0.0435, 0.4033, 0.4728]]])

In [25]:
f.shape

torch.Size([2, 2, 3])

In [26]:
f[0]

tensor([[0.2682, 0.9967, 0.4622],
        [0.3456, 0.1752, 0.2852]])

In [27]:
list(f.shape)

[2, 2, 3]

### Dimension 4 ==> CNN input batch

In [28]:
g = torch.rand(2,3,28,28)
g

tensor([[[[0.6841, 0.7019, 0.4004,  ..., 0.3077, 0.5113, 0.7671],
          [0.2627, 0.4788, 0.5097,  ..., 0.2843, 0.1854, 0.3602],
          [0.0377, 0.6235, 0.6926,  ..., 0.2988, 0.8005, 0.8426],
          ...,
          [0.0269, 0.0946, 0.0222,  ..., 0.3879, 0.0432, 0.2425],
          [0.7563, 0.0305, 0.1489,  ..., 0.9093, 0.4698, 0.3628],
          [0.3704, 0.6158, 0.8513,  ..., 0.8586, 0.1865, 0.3926]],

         [[0.8673, 0.3686, 0.0600,  ..., 0.9495, 0.0831, 0.8484],
          [0.6898, 0.9985, 0.9515,  ..., 0.1995, 0.0982, 0.6573],
          [0.4690, 0.2091, 0.2165,  ..., 0.4767, 0.8519, 0.4088],
          ...,
          [0.5249, 0.0257, 0.5332,  ..., 0.1400, 0.6935, 0.6117],
          [0.5684, 0.6559, 0.2452,  ..., 0.6295, 0.9017, 0.9493],
          [0.9670, 0.2458, 0.9865,  ..., 0.7988, 0.8730, 0.1690]],

         [[0.4146, 0.1919, 0.2917,  ..., 0.6434, 0.8220, 0.1809],
          [0.9472, 0.6239, 0.6513,  ..., 0.5583, 0.4149, 0.2630],
          [0.4253, 0.7904, 0.9220,  ..., 0

In [29]:
g.shape

torch.Size([2, 3, 28, 28])

In [30]:
g.dim()

4

In [31]:
g.numel()

4704