# 05 创建Tensor

In [1]:
import numpy as np
import torch
import warnings
warnings.filterwarnings("ignore")

### import from numpy

In [2]:
a = np.array([2, 3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [3]:
b = np.ones([2,3])
torch.from_numpy(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### import from list

In [4]:
torch.tensor([2, 3.2])

tensor([2.0000, 3.2000])

In [5]:
torch.tensor([[2, 3.2], [1, 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [6]:
torch.FloatTensor([2, 3])

tensor([2., 3.])

In [7]:
torch.FloatTensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### uninitialized  未初始化可能导致数值很大很小，数据需要覆盖，否则容易bug（nan, inf)

In [8]:
torch.empty(2,3,3)

tensor([[[9.3674e-39, 1.0929e-38, 1.0469e-38],
         [8.4490e-39, 1.0102e-38, 9.0919e-39],
         [1.0102e-38, 8.9082e-39, 5.9694e-39]],

        [[8.9082e-39, 1.0194e-38, 9.1837e-39],
         [8.4490e-39, 1.0102e-38, 1.0561e-38],
         [6.8878e-39, 9.4592e-39, 9.9184e-39]]])

In [9]:
torch.Tensor(2,3)

tensor([[6.6021e-07, 5.2598e+22, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [10]:
torch.IntTensor(2,3)

tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.int32)

In [11]:
torch.FloatTensor(2,3)

tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 8.5683e-07, 3.3611e+21]])

### set default type

In [12]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [13]:
torch.Tensor(2,2).type()

'torch.FloatTensor'

In [14]:
torch.set_default_tensor_type(torch.DoubleTensor)        # 增强学习一般使用的是doubletensor，其他一般使用floattensro

In [15]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

### rand/rand_like and randint   
rand=>[0,1]  randint=>[min,max)

In [16]:
c = torch.rand(3,3)
c

tensor([[0.9052, 0.3582, 0.6975],
        [0.7101, 0.2290, 0.4894],
        [0.6181, 0.4408, 0.3918]])

In [17]:
torch.rand_like(c)

tensor([[0.0294, 0.2596, 0.3032],
        [0.9795, 0.4864, 0.5028],
        [0.8868, 0.4081, 0.3286]])

In [18]:
d = torch.randint(1,10,[3,3])
d

tensor([[7, 1, 4],
        [1, 7, 3],
        [8, 6, 7]])

### randn and normal

In [19]:
torch.randn(3,3)

tensor([[ 1.4183,  0.9458, -0.6421],
        [-1.8080, -0.6914,  0.8070],
        [-0.9548, -0.3704,  0.8377]])

In [20]:
torch.normal(mean=torch.full([10],0), std=torch.arange(1, 0, -0.1))

tensor([-1.1944, -1.1020, -0.2909,  0.5819, -0.7128, -0.9199,  0.3434,  0.4069,
        -0.1556,  0.0399])

### full

In [21]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [22]:
torch.full([],7)

tensor(7.)

### arange and range  
arange=>[min,max), range[min,max],不建议使用range

In [23]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [25]:
torch.range(0,10)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### linspace and logspace
linspace=>[min,max]  ,  logspace=>$10^x$

In [26]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [27]:
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [28]:
torch.linspace(0,10,steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
torch.logspace(0,10,steps=11)

tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05,
        1.0000e+06, 1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

### ones,zeros and eye

In [30]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
e = torch.eye(3,4)
e

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [33]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
torch.ones_like(e)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### randperm
random.shuffle 通常用于随机索引，示例为行

In [35]:
torch.randperm(10)

tensor([9, 6, 5, 8, 4, 7, 2, 0, 1, 3])

In [36]:
a = torch.rand(3,6)
a

tensor([[0.3897, 0.5544, 0.1363, 0.4874, 0.8538, 0.3173],
        [0.1211, 0.0695, 0.6700, 0.9498, 0.3812, 0.0768],
        [0.5338, 0.6990, 0.2288, 0.6600, 0.5106, 0.9568]])

In [37]:
b = torch.rand(3,4)
b

tensor([[0.1750, 0.9112, 0.2938, 0.9391],
        [0.6420, 0.0657, 0.9953, 0.2025],
        [0.9951, 0.8775, 0.8535, 0.5299]])

In [38]:
idx = torch.randperm(3)
idx

tensor([2, 1, 0])

In [39]:
a[idx]

tensor([[0.5338, 0.6990, 0.2288, 0.6600, 0.5106, 0.9568],
        [0.1211, 0.0695, 0.6700, 0.9498, 0.3812, 0.0768],
        [0.3897, 0.5544, 0.1363, 0.4874, 0.8538, 0.3173]])

In [40]:
b[idx]

tensor([[0.9951, 0.8775, 0.8535, 0.5299],
        [0.6420, 0.0657, 0.9953, 0.2025],
        [0.1750, 0.9112, 0.2938, 0.9391]])