# 06 create tensor

In [1]:
import numpy as np
import torch

### import from numpy

In [2]:
a = np.array([2, 3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [3]:
b = np.ones([2,3])
torch.from_numpy(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### import from list

In [4]:
torch.tensor([2, 3.2])

tensor([2.0000, 3.2000])

In [5]:
torch.tensor([[2, 3.2], [1, 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [6]:
torch.FloatTensor([2, 3])

tensor([2., 3.])

In [7]:
torch.FloatTensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### uninitialized  未初始化可能导致数值很大很小，数据需要覆盖，否则容易bug（nan, inf)

In [8]:
torch.empty(2,3,3)

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.6115e-43],
         [2.6302e+20, 6.1943e-04, 7.2056e+22]],

        [[2.1720e+29, 1.8057e+28, 5.1412e+31],
         [7.5338e+28, 6.1687e+16, 1.4584e-19],
         [1.4584e-19, 3.1432e-12, 1.3589e-19]]])

In [9]:
torch.Tensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.IntTensor(2,3)

tensor([[  0, 605,   1],
        [  0,   1,   0]], dtype=torch.int32)

In [11]:
torch.FloatTensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### set default type

In [12]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [13]:
torch.Tensor(2,2).type()

'torch.FloatTensor'

In [14]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [15]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

### rand/rand_like and randint   
rand=>[0,1]  randint=>[min,max)

In [16]:
c = torch.rand(3,3)
c

tensor([[0.9694, 0.8832, 0.8264],
        [0.9253, 0.8443, 0.1742],
        [0.7046, 0.3937, 0.1656]])

In [17]:
torch.rand_like(c)

tensor([[0.2505, 0.6483, 0.8999],
        [0.6523, 0.0668, 0.8020],
        [0.1812, 0.3299, 0.6936]])

In [18]:
d = torch.randint(1,10,[3,3])
d

tensor([[1, 8, 4],
        [4, 4, 4],
        [1, 8, 9]])

### randn and normal

In [19]:
torch.randn(3,3)

tensor([[ 0.2220, -0.0791,  0.7941],
        [-0.1718, -1.2316, -0.3250],
        [-0.7369, -0.0310,  0.2606]])

In [20]:
torch.normal(mean=torch.full([10],0), std=torch.arange(1, 0, -0.1))

tensor([ 0.2516, -0.5174,  0.4004,  0.7470,  0.8928, -0.4128, -0.4831, -0.1971,
         0.3362, -0.1426])

### full

In [21]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [22]:
torch.full([],7)

tensor(7.)

### arange and range  
arange=>[min,max), range[min,max],不建议使用range

In [23]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [25]:
torch.range(0,10)

E:\software\Anaconda\Anaconda\envs\Kaggle\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### linspace and logspace
linspace=>[min,max]  ,  logspace=>$10^x$

In [26]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [27]:
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [28]:
torch.linspace(0,10,steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
torch.logspace(0,10,steps=11)

tensor([1.0000e+00, 1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05,
        1.0000e+06, 1.0000e+07, 1.0000e+08, 1.0000e+09, 1.0000e+10])

### ones,zeros and eye

In [30]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [31]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
e = torch.eye(3,4)
e

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [33]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
torch.ones_like(e)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### randperm
random.shuffle 通常用于随机索引，示例为行

In [35]:
torch.randperm(10)

tensor([2, 8, 0, 1, 7, 4, 6, 5, 3, 9])

In [36]:
a = torch.rand(3,6)
a

tensor([[0.7094, 0.5971, 0.0679, 0.1769, 0.0347, 0.2328],
        [0.7697, 0.9135, 0.9299, 0.8814, 0.4542, 0.4024],
        [0.5907, 0.4858, 0.3074, 0.4013, 0.4307, 0.2583]])

In [37]:
b = torch.rand(3,4)
b

tensor([[0.1418, 0.0399, 0.3557, 0.5550],
        [0.9447, 0.2261, 0.4066, 0.1061],
        [0.4425, 0.0167, 0.4833, 0.7686]])

In [38]:
idx = torch.randperm(3)
idx

tensor([1, 0, 2])

In [39]:
a[idx]

tensor([[0.7697, 0.9135, 0.9299, 0.8814, 0.4542, 0.4024],
        [0.7094, 0.5971, 0.0679, 0.1769, 0.0347, 0.2328],
        [0.5907, 0.4858, 0.3074, 0.4013, 0.4307, 0.2583]])

In [40]:
b[idx]

tensor([[0.9447, 0.2261, 0.4066, 0.1061],
        [0.1418, 0.0399, 0.3557, 0.5550],
        [0.4425, 0.0167, 0.4833, 0.7686]])