# 08 维度变换

### View reshape

In [1]:
import torch

In [2]:
a = torch.rand(4, 1, 28, 28)

In [3]:
a.shape

torch.Size([4, 1, 28, 28])

In [4]:
a.view(4, 28*28)

tensor([[0.4106, 0.9996, 0.5487,  ..., 0.2505, 0.3295, 0.9653],
        [0.8303, 0.7100, 0.2380,  ..., 0.5641, 0.8998, 0.6333],
        [0.8934, 0.3797, 0.8364,  ..., 0.3563, 0.0940, 0.0300],
        [0.3491, 0.9041, 0.4301,  ..., 0.5594, 0.2048, 0.2268]])

In [5]:
a.view(4, 28*28).shape

torch.Size([4, 784])

In [6]:
a.view(4*28, 28).shape

torch.Size([112, 28])

In [7]:
a.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [8]:
b = a.view(4,784)

In [9]:
b = a.view(4, 28, 28, 1)  #logic bug

### squeeze and unsqueeze

###### unsqueeze:  [-a.dim()-1, a.dim()+1]    正数在前面插入，负数在后面插入

In [10]:
a.shape

torch.Size([4, 1, 28, 28])

In [11]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [12]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [13]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [14]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [15]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

###### 例子很好，注意tensor里面的是数据，size是 [2]

In [16]:
b = torch.tensor([1.2, 2.3])
b

tensor([1.2000, 2.3000])

In [17]:
b.dim()

1

In [18]:
b.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [19]:
b.unsqueeze(0)

tensor([[1.2000, 2.3000]])

###### for example

In [20]:
b = torch.rand(32)
f = torch.rand(4,32,14,14)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

###### squeeze: 只有1可以挤压

In [21]:
b.shape

torch.Size([1, 32, 1, 1])

In [22]:
b.squeeze().shape

torch.Size([32])

In [23]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [24]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [25]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [26]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

### expand and repeat

###### expand: broadcasting 节约内存推荐， repeat: memory copied  效果一致

In [27]:
a = torch.rand(4,32,14,14)

In [28]:
b.shape

torch.Size([1, 32, 1, 1])

In [29]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

###### 只有维度为1的可以进行扩展， -1表示不变，-4是一个bug

In [30]:
b.expand(-1,32,-1,-1).shape

torch.Size([1, 32, 1, 1])

In [31]:
b.expand(-1,32,-1,-4).shape

torch.Size([1, 32, 1, -4])

###### repeat: 参数是数据复制的次数，这个方法占用内存，慎用

In [32]:
b.shape

torch.Size([1, 32, 1, 1])

In [33]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [34]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [35]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

In [36]:
b.shape

torch.Size([1, 32, 1, 1])

### 交换操作

###### .t 矩阵转置只能用于二维

In [37]:
a = torch.randn(3,4)

In [38]:
a.t()

tensor([[-0.8546,  1.0377,  0.5037],
        [ 0.9743,  0.0360,  1.1603],
        [ 0.8661, -1.1650,  0.5791],
        [ 1.3973,  2.0001,  0.9172]])

###### Transpose

In [39]:
a = torch.randn(4,3,32,32)
a.shape

torch.Size([4, 3, 32, 32])

###### torch.reshape=torch.contiguous.view, view前需要contiguous，view()操作依赖于内存是整块的

###### view()的时候注意顺序变化

In [40]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)

In [41]:
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)

In [42]:
a1.shape,a2.shape

(torch.Size([4, 3, 32, 32]), torch.Size([4, 3, 32, 32]))

In [43]:
torch.all(torch.eq(a,a1))

tensor(0, dtype=torch.uint8)

In [44]:
torch.all(torch.eq(a,a2))

tensor(1, dtype=torch.uint8)

### permute

###### permute和transpose都会打乱内存，在view的时候需要contiguous，permute可以多元交换

In [45]:
a = torch.rand(4,3,28,32)

In [46]:
a.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [47]:
a.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])