# 09 数学运算

### add/minus/multiply/divide matmul pow sqrt/rsqrt round

### basic

In [1]:
import torch

In [2]:
a = torch.rand(3,4)
b = torch.rand(4)
a,b

(tensor([[0.1318, 0.8194, 0.0929, 0.8233],
         [0.2259, 0.8640, 0.1089, 0.9093],
         [0.2429, 0.6418, 0.9774, 0.8375]]),
 tensor([0.1602, 0.3313, 0.1618, 0.2946]))

In [3]:
a+b

tensor([[0.2921, 1.1507, 0.2547, 1.1178],
        [0.3861, 1.1953, 0.2707, 1.2039],
        [0.4032, 0.9731, 1.1392, 1.1321]])

In [4]:
torch.add(a, b)

tensor([[0.2921, 1.1507, 0.2547, 1.1178],
        [0.3861, 1.1953, 0.2707, 1.2039],
        [0.4032, 0.9731, 1.1392, 1.1321]])

In [5]:
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(1, dtype=torch.uint8)

In [6]:
torch.all(torch.eq(a*b, torch.mul(a, b)))

tensor(1, dtype=torch.uint8)

In [7]:
torch.all(torch.eq(a/b, torch.div(a, b)))

tensor(1, dtype=torch.uint8)

###### example:观察一下矩阵乘法以及 broadcasteing

In [8]:
a = torch.tensor([[1.,2.,3.],
                 [4.,5.,6.]])
b = torch.tensor([2.,2.,3.])

In [9]:
a + b, a-b, a*b, a/b, a//b                    #这里乘法还有除法还没有搞懂

(tensor([[3., 4., 6.],
         [6., 7., 9.]]), tensor([[-1.,  0.,  0.],
         [ 2.,  3.,  3.]]), tensor([[ 2.,  4.,  9.],
         [ 8., 10., 18.]]), tensor([[0.5000, 1.0000, 1.0000],
         [2.0000, 2.5000, 2.0000]]), tensor([[0., 1., 1.],
         [2., 2., 2.]]))

### matmul:

###### mm and matmul

In [10]:
a = torch.tensor([[3., 2.,],
                  [4., 5.,]])
b = torch.tensor([[1., 2.],
                  [3., 4.]])

In [11]:
torch.mm(a, b)

tensor([[ 9., 14.],
        [19., 28.]])

In [12]:
torch.all(torch.eq(torch.matmul(a, b),a @ b))

tensor(1, dtype=torch.uint8)

###### for example : 降维

In [13]:
x = torch.rand(4, 784)
w = torch.rand(512, 784)
(x @ (w.t())).shape

torch.Size([4, 512])

###### tensor matmul 模式： 前面不变，后面两维矩阵相乘，前面不一致的 broadcast

In [14]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)
torch.matmul(a, b).shape

torch.Size([4, 3, 28, 32])

In [15]:
b = torch.rand(4, 1, 64, 32)
torch.matmul(a, b).shape

torch.Size([4, 3, 28, 32])

### power

In [16]:
a = torch.full([2,2],3)
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [17]:
aa = a ** 2
aa

tensor([[9., 9.],
        [9., 9.]])

In [18]:
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [19]:
aa.rsqrt()                   # 开方取倒数

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [20]:
aa ** (0.5)

tensor([[3., 3.],
        [3., 3.]])

### exp log

In [21]:
a = torch.exp(torch.ones(2,2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [22]:
torch.log(a)           #默认的log以e为底

tensor([[1., 1.],
        [1., 1.]])

In [23]:
torch.log10(a)

tensor([[0.4343, 0.4343],
        [0.4343, 0.4343]])

### approximation

###### floor ceil round trunc frac

In [24]:
a = torch.tensor(3.14)

In [25]:
a.floor(),a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [26]:
a = torch.tensor(3.499)
a.round()

tensor(3.)

In [27]:
a = torch.tensor(3.5)
a.round()

tensor(4.)

### clamp

###### gradient clipping:   (min),  (min, max)

In [28]:
grad = torch.rand(2, 3)*15
grad

tensor([[ 0.8334, 11.6248, 13.6644],
        [ 0.5527, 13.3240,  3.6036]])

In [29]:
grad.max(),grad.median()

(tensor(13.6644), tensor(3.6036))

In [30]:
grad.clamp(10)

tensor([[10.0000, 11.6248, 13.6644],
        [10.0000, 13.3240, 10.0000]])

In [31]:
grad.clamp(0,10)

tensor([[ 0.8334, 10.0000, 10.0000],
        [ 0.5527, 10.0000,  3.6036]])