# 11 statistics

### norm mearn sun prod max min argmin argmax kthvalue topk

### norm-p 

In [1]:
import torch

In [2]:
a = torch.full([8], 1)
b = a.view(2, 4)
c = a.view(2, 2, 2)
print("a={0},b={1},c={2}".format(a,b,c))

a=tensor([1., 1., 1., 1., 1., 1., 1., 1.]),b=tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),c=tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [3]:
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [4]:
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

###### (m,n,x,y)，dim=3，共有求解了mn个范数

In [5]:
b.norm(1,dim=1),b.norm(2,dim=1)

(tensor([4., 4.]), tensor([2., 2.]))

In [6]:
c.norm(1,dim=0),c.norm(2,dim=0)

(tensor([[2., 2.],
         [2., 2.]]), tensor([[1.4142, 1.4142],
         [1.4142, 1.4142]]))

### mean, sum, min, max, prod

In [7]:
a = torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [8]:
a.min(),a.max(),a.mean()

(tensor(0.), tensor(7.), tensor(3.5000))

In [9]:
a.sum(),a.prod()         #prod所有数据的连乘

(tensor(28.), tensor(0.))

### argmin and argmax

###### 不指定维度的时候，打平求最大，最小位置

In [10]:
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [11]:
a = torch.randn(4, 10)
a

tensor([[-0.5768, -1.5699, -1.3377,  2.1877, -1.2263,  1.6034,  0.7762, -0.1412,
         -1.9647,  0.3147],
        [ 1.8476,  0.1734,  0.9731, -0.7234, -1.8285,  0.7657,  1.0314,  0.4843,
         -2.3134, -0.5060],
        [ 0.7452, -0.1633, -0.2266, -1.2185, -0.6917, -0.4515,  0.9147, -0.2686,
          0.8473,  0.7926],
        [-1.2314, -0.0961,  0.7711, -0.6197,  0.7915, -1.0238,  0.8308,  1.8490,
          2.3395,  0.7049]])

In [12]:
a.argmax(),a.argmax(dim=1),a.argmax(dim=0)

(tensor(38), tensor([3, 0, 6, 8]), tensor([1, 1, 1, 0, 3, 0, 1, 3, 3, 2]))

### dim and keepdim

###### argmax其实是max的一部分

In [13]:
a.max(dim=1)

torch.return_types.max(
values=tensor([2.1877, 1.8476, 0.9147, 2.3395]),
indices=tensor([3, 0, 6, 8]))

In [14]:
a.argmax(dim=1)

tensor([3, 0, 6, 8])

###### keepdim=True, 保持维度

In [15]:
a.max(dim=1,keepdim=True)

torch.return_types.max(
values=tensor([[2.1877],
        [1.8476],
        [0.9147],
        [2.3395]]),
indices=tensor([[3],
        [0],
        [6],
        [8]]))

In [16]:
a.argmax(dim=1, keepdim=True)

tensor([[3],
        [0],
        [6],
        [8]])

### top-k and k-th

###### topk 相当于max的延申，可以提取前若干个或者后若干个(largest=False)的值和位置

In [17]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[2.1877, 1.6034, 0.7762],
        [1.8476, 1.0314, 0.9731],
        [0.9147, 0.8473, 0.7926],
        [2.3395, 1.8490, 0.8308]]),
indices=tensor([[3, 5, 6],
        [0, 6, 2],
        [6, 8, 9],
        [8, 7, 6]]))

In [18]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[-1.9647, -1.5699, -1.3377],
        [-2.3134, -1.8285, -0.7234],
        [-1.2185, -0.6917, -0.4515],
        [-1.2314, -1.0238, -0.6197]]),
indices=tensor([[8, 1, 2],
        [8, 4, 3],
        [3, 4, 5],
        [0, 5, 3]]))

###### kthvalue: 第 K小

In [19]:
a.kthvalue(8, dim=1)           #对于10个元素的，第8小就是第3大，可以和上面对上。

torch.return_types.kthvalue(
values=tensor([0.7762, 0.9731, 0.7926, 0.8308]),
indices=tensor([6, 2, 9, 6]))

In [20]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([-1.3377, -0.7234, -0.4515, -0.6197]),
indices=tensor([2, 3, 5, 3]))

In [21]:
a.kthvalue(3,dim=1)

torch.return_types.kthvalue(
values=tensor([-1.3377, -0.7234, -0.4515, -0.6197]),
indices=tensor([2, 3, 5, 3]))

### compare

In [22]:
a>0

tensor([[0, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        [1, 1, 1, 0, 0, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
        [0, 0, 1, 0, 1, 0, 1, 1, 1, 1]], dtype=torch.uint8)

In [23]:
torch.gt(a,0)

tensor([[0, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        [1, 1, 1, 0, 0, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
        [0, 0, 1, 0, 1, 0, 1, 1, 1, 1]], dtype=torch.uint8)

In [24]:
a!=0

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

###### eq and equal

In [25]:
a = torch.ones(2,3)
b = torch.randn(2,3)

In [26]:
torch.eq(a, b)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [27]:
torch.eq(a,a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [28]:
torch.equal(a,a)

True