# 11 高阶操作

### where 

###### torch.where (condition, x, y) ==> Tensor  高度并行

In [1]:
import torch

In [2]:
cond = torch.tensor([[0.6769, 0.7271],
                     [0.8884, 0.4163]])
a = torch.zeros(2, 2)
b = torch.ones(2, 2)

In [3]:
torch.where(cond>0.5, a, b)

tensor([[0., 0.],
        [0., 1.]])

### gather

###### torch.gather (input, dim, index, out=None) ==> Tensor    相当于查表

###### for example: retrieve global label

In [4]:
prob = torch.randn(4,10)

In [5]:
idx = prob.topk(dim=1, k=3)
idx

torch.return_types.topk(
values=tensor([[ 2.1400,  0.4812, -0.0464],
        [ 1.3737,  1.0333,  0.8548],
        [ 1.7324,  1.6800,  1.5744],
        [ 0.6896,  0.6248,  0.5842]]),
indices=tensor([[4, 9, 2],
        [5, 1, 2],
        [8, 3, 2],
        [6, 3, 5]]))

In [6]:
idx = idx[1]
idx

tensor([[4, 9, 2],
        [5, 1, 2],
        [8, 3, 2],
        [6, 3, 5]])

In [7]:
label = torch.arange(10)+100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [8]:
torch.gather(label.expand(4,10),dim=1,index=idx.long())

tensor([[104, 109, 102],
        [105, 101, 102],
        [108, 103, 102],
        [106, 103, 105]])