# 13 activation functions

### sigmoid / logistic

导数形式：$\delta'(x)=\delta(1-\delta)$ ，这个函数在较大值时，导数基本为0，梯度下降不会得到很好的更新。

In [1]:
import torch
import torch.nn.functional as F           #提取sigmoid等函数

In [2]:
a = torch.linspace(-100,100,10)
a

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5555,   77.7778,  100.0000])

In [3]:
torch.sigmoid(a)

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

### tanh (在RNN中应用较多）

$f(x)=tanh(x)=\frac{e^x-e^{-x}}{e^x+e^{-x}}=2sigmoid(2x)-1$

$f'(x)=1-tanh^2(x)$

In [4]:
a = torch.linspace(-1,1,10)
torch.tanh(a)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

### Rectified Linear Unit =Relu (常用)

$f(x)=\begin{cases} 
		0, & for\ x<0\\ 
		x, & for\ x\ge0 
	\end{cases}$

In [5]:
a = torch.linspace(-1,1,10)
torch.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [6]:
F.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])